version: "3.8"
services:
  db:
    build:
      context: ./config/db
      dockerfile: Dockerfile
      args:
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - ADMIN_PASSWORD=$ADMIN_PASSWORD
    container_name: "local-webapp-db"
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    # env_file: ./config/db/.env.local
    expose:
      - 5432
    ports:
      - $DB_PORT:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: ./config/db/pg_password.txt
