version: "3.8"
services:
  webapp:
    build:
      context: .
      args:
        HTTPS_PROXY: http://192.168.31.130:1089
    environment:
      DB_CONTAINER_NAME: "webapp-db-1"
      DB_HOST: "db"
      DB_PORT: 5432
    container_name: "webapp-app-1"
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - .:/usr/src/app
  db:
    image: postgres:15.4
    container_name: "webapp-db-1"
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 8088:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: ./config/pg_password.txt
