version: "3.8"
services:
  webapp:
    build:
      context: .
      args:
        GOPROXY: "https://goproxy.cn,direct"
    environment:
      DB_CONTAINER_NAME: "webapp-db-1"
      DB_HOST: "db"
      DB_PORT: 5432
      DOMAIN_NAME: $DOMAIN_NAME
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      ADMIN_PASSWORD: $ADMIN_PASSWORD
      USER_DEFAULT_PASSWORD: $USER_DEFAULT_PASSWORD
    container_name: "webapp-app-1"
    # ports:
    #   - $APP_PORT:3000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:15.4
    container_name: "local-webapp-db"
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/db/initdb:/docker-entrypoint-initdb.d:ro
      - ./config/db:/tmp/data:ro
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
    # ports:
    #   - $DB_PORT:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:1.25.2-alpine
    container_name: "local-nginx"
    environment:
      - APP_LOCAL_HOST=webapp
      - NGINX_PORT=$NGINX_PORT
    volumes:
      - ./static:/data/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/logs:/etc/nginx/logs
    ports:
      - 3004:$NGINX_PORT
    depends_on:
      - webapp

volumes:
  db-data:
