version: "3.8"
services:
  db:
    image: postgres:15.4
    container_name: "local-webapp-db"
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/db/initdb:/docker-entrypoint-initdb.d/
      - ./config/db:/tmp/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - USER_DEFAULT_PASSWORD=$USER_DEFAULT_PASSWORD
      - PGTZ=UTC
    ports:
      - $DB_PORT:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.25.2-alpine
    container_name: "local-nginx"
    environment:
      - APP_LOCAL_HOST=172.17.0.1
      - APP_PORT=$APP_PORT
    volumes:
      - ./static:/data/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates/webapp.dev.conf.template:/etc/nginx/templates/webapp.conf.template:ro
      - ./nginx/logs:/etc/nginx/logs
    ports:
      - $NGINX_PORT:80

  redis:
    image: kholinchen/credis:latest
    container_name: "local-redis"
    environment:
      - REDIS_USER=$REDIS_USER
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDISCLI_AUTH=$REDISCLI_AUTH
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - $REDIS_PORT:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  redis-data:
