modules:
  - article
  - reply
  - user
  - manage
  - role
  - permission

data:
  article:
    create:
      name: Create Article
      adapt_id: article.create # adapt_id is used to adapt with backend permission front id
      enabled: true
    edit_mine:
      name: Edit Article of Myself
      adapt_id: article.edit_mine
      enabled: true
    edit_others:
      name: Edit Article of Others
      adapt_id: article.edit_others
      enabled: false
    delete_mine:
      name: Delete Article of Myself
      adapt_id: article.delete_mine
      enabled: true
    delete_others:
      name: Delete Article of Others
      adapt_id: article.delete_others
      enabled: false
    save:
      name: Save Article
      adapt_id: article.save
      enabled: true
    vote_up:
      name: Vote Up Article
      adapt_id: article.vote_up
      enabled: true
    vote_down:
      name: Vote Down Article
      adapt_id: article.vote_down
      enabled: false
    react:
      name: React Article
      adapt_id: article.react
      enabled: true
    reply:
      name: Reply Article
      adapt_id: article.reply
      enabled: true
  
  reply:
    create:
      name: Create Reply
      adapt_id: reply.create
      enabled: true
    edit_mine:
      name: Edit Reply of Myself
      adapt_id: reply.edit_mine
      enabled: true
    edit_others:
      name: Edit Reply of Others
      adapt_id: reply.edit_others
      enabled: false
    delete_mine:
      name: Delete Reply of Myself
      adapt_id: reply.delete_mine
      enabled: true
    delete_others:
      name: Delete Reply of Others
      adapt_id: reply.delete_others
      enabled: false
    save:
      name: Save Reply
      adapt_id: reply.save
      enabled: true
    vote_up:
      name: Vote Up Reply
      adapt_id: reply.vote_up
      enabled: true
    vote_down:
      name: Vote Down Reply
      adapt_id: reply.vote_down
      enabled: false
    react:
      name: React Reply
      adapt_id: reply.react
      enabled: true
    reply:
      name: Reply Reply
      adapt_id: reply.reply
      enabled: true
  
  user:
    list_access:
      name: Acess User List
      adapt_id: user.list_access
      enabled: false
    ban:
      name: Ban User
      adapt_id: user.ban
      enabled: false
    update_intro_mine:
      name: Update User Intro of Myself
      adapt_id: user.update_intro_mine
      enabled: true
    update_intro_others:
      name: Update User Intro of Others
      adapt_id: user.update_intro_others
      enabled: false
    update_role:
      name: Update User Role of All
      adapt_id: user.update_role
      enabled: false

  manage:
    access:
      name: Access Manage
      adapt_id: manage.access
      enabled: false

  permission:
    access:
      name: Access Permission
      adapt_id: permission.access
      enabled: false
    add:
      name: Add Permission
      adapt_id: permisison.add
      enabled: false

  role:
    access:
      name: Access Role
      adapt_id: role.access
      enabled: false
    add:
      name: Add Role
      adapt_id: role.add
      enabled: false
    edit:
      name: Edit Role
      adapt_id: role.edit
      enabled: false
      
