role_id_list:
  - common_user
  - banned_user
  - moderator
  - admin
data:
  base:
    type: group
    name: Base
    adapt_id: base # adapt_id is used to adapt with backend role front id
    permissions:
      - article.create # backend permission front id
      - article.reply
      - article.edit_mine
      - article.save
      - article.react
      - article.delete_mine
      - article.vote_up
      - reply.create
      - reply.reply
      - reply.edit_mine
      - reply.save
      - reply.react
      - reply.delete_mine
      - reply.vote_up
      - user.update_intro_mine

  moderate:
    type: group
    name: Moderate
    adapt_id: moderate
    permissions:
      - article.edit_others
      - article.delete_others
      - reply.edit_others
      - reply.delete_others
      - user.manage
      - user.ban
      - user.update_intro_others

  site_manage:
    type: group
    name: Site Manage
    adapt_id: site_manage
    permissions:
      - user.list_access
      - user.set_moderator
      - user.set_admin
      - manage.access
      - permission.access
      - role.access
      - role.add
      - role.edit
      
  common_user:
    type: role
    name: Common User
    adapt_id: common_user
    groups:
      - base
    permissions:
  
  banned_user:
    type: role
    name: Banned User
    adapt_id: banned_user
    groups:
    permissions:
      
  moderator:
    type: role
    name: Moderator
    adapt_id: moderator
    groups:
      - base
      - moderate
    permissions:
  
  admin:
    type: role
    name: Admin
    adapt_id: admin
    groups:
      - base
      - moderate
      - site_manage
    permissions:

