# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy to prod

on:
  release:
    types: [published]
    tags:
      - v*

jobs:
  restart_app:
    name: Restart app
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: kholinchen/dproject
          tags: |
            type=semver,pattern={{version}}
            
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        env:
          APP_VERSION: ${{ steps.meta.outputs.version }}
        with:
          host: ${{ secrets.PROD_APP_HOST }}
          username: ${{ secrets.PROD_HOST_USERNAME }}
          key: ${{ secrets.PROD_HOST_KEY }}
          port: ${{ secrets.PROD_HOST_SSH_PORT }}
          script: |
            $HOME/go/src/github.com/oodzchen/dproject/scripts/restart_app.sh
            docker ps
