# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy to prod

on:
  release:
    types: [published]
    tags:
      - v*

jobs:
  restart_app:
    name: Restart app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract tag
        id: vars
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          TAG="${GITHUB_REF#refs/*/v}"
          echo "TAG: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
            
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_APP_HOST }}
          username: ${{ secrets.PROD_HOST_USERNAME }}
          key: ${{ secrets.PROD_HOST_KEY }}
          port: ${{ secrets.PROD_HOST_SSH_PORT }}
          script: |
            echo "output tag: " ${{ steps.vars.outputs.tag }}
            APP_VERSION=${{ steps.vars.outputs.tag }}
            echo "APP_VERSION: $APP_VERSION"
            APP_VERSION=${{ steps.vars.outputs.tag }} $HOME/go/src/github.com/oodzchen/dproject/scripts/restart_app.sh
            docker ps
